# -*- coding: utf-8 -*-
"""MBA_BI_BIG_DATA_UNIPE_titanic_model_survived_notebook_WANDEILSON_FERREIRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRJvLLXkP8RLSWiDkNTNcAeGuco_EbKn

## Importando as bibliotecas necessárias para o desenvolvimento

Importando as bibliotecas necessárias para o desenvolvimento
"""

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

# Feature Scaling
from sklearn.preprocessing import StandardScaler

# TO DO: Importar biblioteca de LogisticRegression do sklearn
from sklearn.linear_model import LogisticRegression


# Making the confusion Matrix
from sklearn.metrics import confusion_matrix

# Bibliotecas de vizualização de dados
import seaborn as sns
# import missingno as msno
import matplotlib.pyplot as plt

print(pd.__version__)
print(np.__version__)

"""
## Realizando a carga dos dados
"""

# TO DO: Realizar a carga dos dados do arquivo titanic.csv
titanic = pd.read_csv("/content/titanic.csv")

titanic.head()

#Análise Exploratória dos Dados
# TO DO: Apresentar informações estatísticas descritivas do dataste
titanic.describe()

"""## Início da Análise Exploratória de Dados

"""

distribution = sns.countplot(x='survived', data = titanic)

# Apagando os atributos que não interessam a modelagem
# TO DO: Realizar a exclusão dos atributos (colunas) 'name', 'ticket' e 'cabin'
colunas_deletadas = ['name', 'ticket','cabin']
titanic = titanic.drop(colunas_deletadas, axis=1)

titanic.head()

"""## Resolver valores ausentes - Missing Values"""

#Identifcando valores ausentes
print('-- Antes do tratamento --')
print(titanic.isnull().sum())

# print(titanic['pclass'].count())

# possibilidade 1 - Apagar os registros que contém valores ausentes
# TO DO: Realizar a exclusão dos registros com valores ausentes b
titanic = titanic.dropna()

# TO DO: Realizar a exclusão dos registros com valores ausentes b
print('-- Depois do tratamento --')
titanic = titanic.dropna()
print(titanic.isnull().sum())

print('-- Informações sobre o dataset --')
titanic.info()

"""## Substituindo os valores categóricos (nominais) por valores numéricos

A função get_dummies do pacote pandas converte variáveis categóricas em variáveis dummy / indicadoras.



"""

#Substituindo os valores categóricos (nominais) por valores numéricos - Dummy encoding
titanic = pd.get_dummies(titanic)

titanic.head()

from IPython.display import display

#Usando o método loc com lógica booleana. Pegando todas as colunas diferentes de "survived"
X = titanic.loc[:,titanic.columns!="survived"].values
y = titanic.iloc[:, 5].values

display(X)
display(y)

#Separação do dataset em treinamento e tests
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.30,
                                                    random_state=0)

"""## Feature Scaling

Uma das transformações mais importantes que você precisa aplicar aos seus dados é o dimensionamento de recursos (feature scaling). Com poucas exceções, os algoritmos de Aprendizado de Máquina não apresentam bom desempenho quando os atributos numéricos de entrada possuem escalas muito diferentes. Este é o caso da habitação. Dados: o número total de salas varia de cerca de 6 a 39.320, enquanto a renda média varia apenas de 0 a 15. Observe que o escalonamento dos valores-alvo geralmente não é necessário.
"""

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

display(X_train)
display(X_test)

"""## Criando o classificador de Logistic Regression para o conjunto de treinamento

"""

# TO DO: Instanciar um classificador para Regressão Logística (Logistic Regression)
#Parametros para o classificador random_state=0 e solver='lbfgs'
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
# Trainando o modelo
classifier.fit(X_train, y_train)

# Prevendo alguns valores com o conjunto de dados de teste

#Sem indicação de probabilidade
y_pred = classifier.predict(X_test)
y_pred

"""## Criando uma Matriz de Confusão para analisar o resultado da previsão feita pelo modelo

Podemos resumir nosso modelo de "predição de lobo" usando uma matriz de confusão 2x2 que descreve TO DOs os quatro resultados possíveis:

> Um verdadeiro positivo (TP) é um resultado em que o modelo prevê corretamente a classe positiva. Da mesma forma, um verdadeiro negativo é um resultado em que o modelo prevê corretamente a classe negativa.

> Um falso positivo (FP) é um resultado em que o modelo prevê incorretamente a classe positiva. E um falso negativo é um resultado em que o modelo prediz incorretamente a classe negativa.
"""

# Making the confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

"""## Verificando a acurácia do modelo utilizado

Precisão é uma métrica para avaliar modelos de classificação. Informalmente, a precisão é a fração de previsões que nosso modelo acertou.
"""

# Acurácia do Logistic Regression

from sklearn.metrics import accuracy_score

for clf in (classifier,):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

