# -*- coding: utf-8 -*-
"""MBA_BI_BIG_DATA_UNIPE_Outlier_Detection_WANDEILSON_FERREIRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_z2NXKM3na_800fZOgrFDo2yv1IOBET
"""

# TO DO: Instalação da biblioteca do pyod. Excutada uma única vez.
#!pip install pyod

# Commented out IPython magic to ensure Python compatibility.
# -- Bibliotecas de tratamento de dados --
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

# -- Bibliotecas de Vizualização de dados --
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# -- Importação do método para detecção de anomalias --
from pyod.models.iforest import IForest

print(pd.__version__)
print(np.__version__)

hr = pd.read_csv('HR.csv')

# TO DO: oberter um sample dos dados.
hr.head()

hr.describe().T

#Verificando valores ausentes
print(hr.isnull().sum())

hr.shape

hr.info()

# TO DO: Deixar todos os nomes de colunas em maiúsculas.
hr.columns = hr.columns.str.upper()
hr.columns

"""## Aplicando Label Enconding


Fonte: https://towardsdatascience.com/categorical-encoding-using-label-encoding-and-one-hot-encoder-911ef77fb5bd
"""

hr.columns = hr.columns.str.upper()
hr.columns

# CRIANDO UMA INSTÂNCIA DA CLASSE LabelEncoder do sci-kit learn
labelencoder = LabelEncoder()

# Assigning numerical values and storing in another column
hr['SALES'] = labelencoder.fit_transform(hr['SALES'])

# Assigning numerical values and storing in another column
hr['SALARY'] = labelencoder.fit_transform(hr['SALARY'])

hr.head()

# hr.LEFT = hr.LEFT.astype('category')
# hr.info()

"""## Detecção de Outliers de forma visual"""

# Schema de cores possíveis
# ['Alphabet',
#  'Antique',
#  'Bold',
#  'D3',
#  'Dark2',
#  'Dark24',
#  'G10',

fig = px.scatter(hr,
                 x='LAST_EVALUATION',
                 y='AVERAGE_MONTLY_HOURS',
                 color='LEFT',
                 color_discrete_sequence=px.colors.qualitative.Antique
                 )

fig.show()

# TO DO: Utilizar um boxplot para verificação de outliers.

"""## Aplicação do modelo IsolationForeset para Deteção de Anomalias"""

#TO DO: Aplicação do algoritmo para detecção de anomalias
import plotly.express as px
fig = px.box(hr,
             y = 'SATISFACTION_LEVEL')
fig.show()

# classificação de quem é outliers ou não
outliner_detection_clf = IForest(contamination=0.05, #Porcentagem de outliers que desejamos encontrar na amostra
                             random_state = 42,
                             verbose=True)

outliner_detection_clf.fit(hr)

y_pred = outliner_detection_clf.predict(hr)

# Contando os outliers
n_outliers = np.count_nonzero(y_pred ==1)

print(f'\nExistem {n_outliers} outliners dentro dessa amostra\n')
#print("número de outliders:", n_outliers)

# TO DO:  Mostrar a quantidade de outliers e não outliers
#np.unique(y_pred, return_counts=True)

out = hr.loc[hr['OUTLIERS'] == 1]
print(f'Quantidade de outliers: {(len(out))}')

y_pred

# TO DO: Criando uma nova coluna para classificação dos outliers (0 = inliders, 1 = outliers).
hr['OUTLIERS'] = y_pred.tolist()

hr.head()

# TO DO: Apresentando somente os X% de outliers identificados no conjunto de dados.
out = hr.loc[hr['OUTLIERS'] == 1] #Contando a quantidade de outliers
p_outliers = (out / len(hr['OUTLIERS']))*100
print(f'\ Porcentagem de outliers {p_outliers} da amostra\n')