# -*- coding: utf-8 -*-
"""Atividade_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDTZkKTx7AstwyIQOmSctE2i0LzFWpoR
"""

import pandas as pd
pd.set_option('display.max_columns', None)

ocorrencia = pd.read_csv('/content/ocorrencia.csv', encoding="ISO-8859-1", sep=';')

ocorrencia.tail()

ocorrencia['total_aeronaves_envolvidas'].describe()

ocorrencia.count().isnull()

ocorrencia[['ocorrencia_aerodromo','ocorrencia_cidade', 'ocorrencia_uf']].value_counts()

#ocorrencia.drop(columns=['codigo_ocorrencia1','codigo_ocorrencia2','codigo_ocorrencia3','codigo_ocorrencia4'])
ocorrencia_drop = ocorrencia.drop(columns=['codigo_ocorrencia1','codigo_ocorrencia2','codigo_ocorrencia3','codigo_ocorrencia4'])
ocorrencia_drop.head(20)

ocorrencia_drop.value_counts()

#ocorrencia_drop['ocorrencia_saida_pista'].value_counts()
ocorrencia_drop['total_aeronaves_envolvidas'].value_counts()

[['ocorrencia_classificacao',	'ocorrencia_cidade', 'ocorrencia_uf',	'ocorrencia_aerodromo',	'ocorrencia_dia',	'ocorrencia_hora', investigacao_aeronave_liberada	investigacao_status	divulgacao_relatorio_numero	divulgacao_relatorio_publicado	divulgacao_dia_publicacao	total_recomendacoes	total_aeronaves_envolvidas	ocorrencia_saida_pista